apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-plugin
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
    spec:
      serviceAccountName: kubeflux
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
      - key: "node-role.kubernetes.io/master"
      containers:
        - image: quay.io/cmisale/kubeflux:latest
          imagePullPolicy: Always
          command:
          - /bin/kube-scheduler
          - --leader-elect=false
          - --config=/home/sched-config.yaml
          - -v=9
          name: schedulingplugin
          securityContext:
            privileged: true
      hostNetwork: false
      hostPID: false
